INSERT INTO todo_item (titulo, detalhes, data, prioridade) VALUES ('Tarefa aula 1', 'Completar nossa API', '2024-04-15 22:00:00', 'Normal');
INSERT INTO todo_item (titulo, detalhes, data, prioridade) VALUES ('Ler um livro - técnico', 'Ler o livro Código Limpo', '2024-04-30 19:00:00', 'Normal');
INSERT INTO todo_item (titulo, detalhes, data, prioridade) VALUES ('Ler um livro - cotidiano', 'O poder do hábito', '2024-04-30 19:00:00', 'Normal');
INSERT INTO todo_item (titulo, detalhes, data, prioridade) VALUES ('Ver um filme', 'Matrix', '2024-04-20 22:00:00', 'Normal');
INSERT INTO todo_item (titulo, detalhes, data, prioridade) VALUES ('Ver um filme', 'A Origem', '2024-04-25 23:00:00', 'Normal');
INSERT INTO todo_item (titulo, detalhes, data, prioridade) VALUES ('Finalizar o projeto do projeto', 'Nosso projeto', '2024-04-17 19:00:00', 'Normal');
INSERT INTO todo_item (titulo, detalhes, data, prioridade) VALUES ('Ir ao café', 'Tomar um cafezinho e apreciar a rua', '2024-04-16 09:00:00', 'Normal');
INSERT INTO todo_item (titulo, detalhes, data, prioridade) VALUES ('Dar uma volta', 'Andar pela cidade como um turista', '2024-04-19 10:00:00', 'Normal');
INSERT INTO todo_item (titulo, detalhes, data, prioridade) VALUES ('Levar o cachorro pra passear', 'Viva os doguinhos!', '2024-04-16 10:00:00', 'Normal');
INSERT INTO todo_item (titulo, detalhes, data, prioridade) VALUES ('Pizza e cerveja', 'Completar nossa API', '2024-04-26 19:00:00', 'Normal');