CREATE TABLE todo_item
(
    id         INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid       UUID DEFAULT RANDOM_UUID(),
    titulo     VARCHAR(255),
    detalhes   VARCHAR(255),
    data       TIMESTAMP,
    concluido  BOOLEAN DEFAULT FALSE,
    prioridade VARCHAR(255),
    CONSTRAINT pk_todoitem PRIMARY KEY (id)
);